name: Build and push to Artifact Registry

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    env:
      REGION: europe-west3
      APP_NAME: ${{ github.event.repository.name }}

    permissions:
      id-token: write
      contents: read

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: authorize
        name: Authorize using Workflow Identity Federation
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}
          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}

      - id: login
        name: Login to Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.authorize.outputs.access_token }}

      - id: push
        name: Build and push to Artifact Registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/docker/${{ env.APP_NAME }}:latest

      - id: deploy
        name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.APP_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/docker/${{ env.APP_NAME }}:latest
          flags: --service-account=hello-default-sa@${{ vars.PROJECT_ID }}.iam.gserviceaccount.com

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
